# Generated by Django 5.1.5 on 2025-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filter', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='portfolios')),
                ('link', models.CharField(max_length=400)),
                ('category', models.ManyToManyField(to='portfolio_app.category')),
            ],
            options={
                'verbose_name_plural': 'Portfoliolar',
                'ordering': ['-id'],
            },
        ),
    ]
